import type { EmploymentType } from "@hr-system/shared";
import type { Timestamp } from "firebase-admin/firestore";
import type { Employee } from "../types.js";

type EmployeeSeed = Omit<Employee, "hireDate" | "createdAt" | "updatedAt"> & {
  hireDate?: Timestamp;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
};

/**
 * ACG実在スタッフ・従業員のseedデータ
 * googleChatUserId はタスク管理シートの「{userId}.{表示名}」から取得
 * employeeNumber は社員番号（正確な番号が確認でき次第更新）
 */
export const TEST_EMPLOYEES: EmployeeSeed[] = [
  // ===== 人事・管理スタッフ =====
  {
    employeeNumber: "EMP-1443",
    name: "徳永 誠",
    email: null,
    googleChatUserId: "users/1443",
    employmentType: "full_time" as EmploymentType,
    department: "人事部",
    position: "人事担当",
    isActive: true,
  },
  {
    employeeNumber: "EMP-1412",
    name: "坂口 愛佳",
    email: null,
    googleChatUserId: "users/1412",
    employmentType: "full_time" as EmploymentType,
    department: "人事部",
    position: "人事担当",
    isActive: true,
  },
  {
    employeeNumber: "EMP-2065",
    name: "大島 功嗣",
    email: null,
    googleChatUserId: "users/2065",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: "管理担当",
    isActive: true,
  },
  {
    employeeNumber: "EMP-0019",
    name: "重 はるか",
    email: null,
    googleChatUserId: "users/19",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  // ===== 有川チーム =====
  {
    employeeNumber: "EMP-0159",
    name: "有川 智浩",
    email: null,
    googleChatUserId: "users/159",
    employmentType: "full_time" as EmploymentType,
    department: "有川チーム",
    position: "チームリーダー",
    isActive: true,
  },
  {
    employeeNumber: "EMP-0061",
    name: "山本 亜湖",
    email: null,
    googleChatUserId: "users/61",
    employmentType: "full_time" as EmploymentType,
    department: "有川チーム",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-0206",
    name: "河口 修一朗",
    email: null,
    googleChatUserId: "users/206",
    employmentType: "full_time" as EmploymentType,
    department: "有川チーム",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-1766",
    name: "中村 隼人",
    email: null,
    googleChatUserId: "users/1766",
    employmentType: "full_time" as EmploymentType,
    department: "有川チーム",
    position: null,
    isActive: true,
  },
  // ===== 各拠点スタッフ =====
  {
    employeeNumber: "EMP-0455",
    name: "西 裕介",
    email: null,
    googleChatUserId: "users/455",
    employmentType: "full_time" as EmploymentType,
    department: "博多拠点",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-1970",
    name: "中村 智子",
    email: null,
    googleChatUserId: "users/1970",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-1370",
    name: "坂口 真理",
    email: null,
    googleChatUserId: "users/1370",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-0677",
    name: "谷口 みのり",
    email: null,
    googleChatUserId: "users/677",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-1509",
    name: "宇都宮 光寿",
    email: null,
    googleChatUserId: "users/1509",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-1608",
    name: "前田 由紀子",
    email: null,
    googleChatUserId: "users/1608",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-0115",
    name: "小松 利香",
    email: null,
    googleChatUserId: "users/115",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-0387",
    name: "市原 玄",
    email: null,
    googleChatUserId: "users/387",
    employmentType: "full_time" as EmploymentType,
    department: "管理部",
    position: null,
    isActive: true,
  },
  // ===== 訪問看護・介護職員（代表例）=====
  {
    employeeNumber: "EMP-P001",
    name: "介護スタッフA",
    email: null,
    googleChatUserId: null,
    employmentType: "part_time" as EmploymentType,
    department: "介護部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-P002",
    name: "介護スタッフB",
    email: null,
    googleChatUserId: null,
    employmentType: "part_time" as EmploymentType,
    department: "介護部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-N001",
    name: "訪問看護師A",
    email: null,
    googleChatUserId: null,
    employmentType: "visiting_nurse" as EmploymentType,
    department: "訪問看護部",
    position: null,
    isActive: true,
  },
  {
    employeeNumber: "EMP-N002",
    name: "訪問看護師B",
    email: null,
    googleChatUserId: null,
    employmentType: "visiting_nurse" as EmploymentType,
    department: "訪問看護部",
    position: null,
    isActive: true,
  },
];
